### PR TITLE
service-deployment

### PR DESCRIPTION
**Pull request by ashishrawat-ar**

### CODE REVIEW

**Comment by nxsudarshan** [comment]
Are you created your own confimaps and secrets?

**Comment by ashishrawat-ar** [comment]
> 

Yes sir, but it was with the help of online tuts.

**Comment by nxsudarshan** [comment]
@ashishrawat-ar yes you can use online tuts but in this repo only your code need to push, tuts code not to push here.

**Comment by ashishrawat-ar** [comment]
okay sir, i will take care of that.

**Pull request merged**
